// 显示硬件接口

use base.types.{result, buffer, color}
use base.error.{Error}

// 显示接口
interface display {
  // 初始化显示设备
  init: func() -> result<unit, Error>
  // 获取显示分辨率
  get_resolution: func() -> result<{width: u32, height: u32}, Error>
  // 刷新屏幕
  refresh: func(buffer: buffer) -> result<unit, Error>
  // 设置背景色
  set_background: func(color: color) -> result<unit, Error>
  // 绘制像素
  draw_pixel: func(x: u32, y: u32, color: color) -> result<unit, Error>
  // 绘制矩形
  draw_rect: func(x: u32, y: u32, width: u32, height: u32, color: color) -> result<unit, Error>
  // 清除屏幕
  clear: func() -> result<unit, Error>
  // 关闭显示设备
  deinit: func() -> result<unit, Error>
}

// 显示设备世界
world display {
  import display
}
