// 智能摄像头接口定义

use base.types.{result, list}
use base.error.{Error}
use yiduo:unihal.{sensor_data}

package yiduo:apps:smart_camera;

/// 图像数据
type image = list<u8>;

/// 智能摄像头接口
interface camera {
    /// 捕获图像
    capture: func() -> result<image, Error>;
    
    /// 开始录制
    start_recording: func() -> result<unit, Error>;
    
    /// 停止录制
    stop_recording: func() -> result<unit, Error>;
    
    /// 获取设备信息
    get_info: func() -> result<string, Error>;
}

// 智能摄像头世界
world smart_camera {
  import camera
}
