# Yiduo OS - WAMR Build Script
#
# Self-bootstrapping: reads component configuration (008 spec)
# from wamr-runtime.yaml, derives ALL build parameters from it.
#
# Usage:
#   .\scripts\build_wamr.ps1               # auto (reads bootstrap.yaml)
#   .\scripts\build_wamr.ps1 -Stub          # force stub
#   .\scripts\build_wamr.ps1 -SkipClone     # skip git clone

param(
    [switch]$Stub = $false,
    [switch]$Rebuild = $false,
    [switch]$SkipClone = $false
)

$ErrorActionPreference = "Continue"
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition
$projectRoot = Resolve-Path "$scriptDir/.."

$bootstrapPath = Join-Path $projectRoot "configs/bootstrap.yaml"
$wamrConfigPath = Join-Path $projectRoot "configs/components/wamr-runtime.yaml"
$moonPkgAbs = Join-Path $projectRoot "runtime/wamr/moon.pkg"

# 鈹€鈹€鈹€ Read Component Config via yaml_query (自举递归解析器) 鈹€鈹€鈹€
function Get-BuildMetadata($yamlPath, $implName) {
    $projectRoot = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $yamlPath))
    $buildDir = Join-Path $projectRoot "_build"
    $yamlQueryExe = Join-Path $projectRoot "_build/native/debug/build/tools/yaml_query/yaml_query.exe"
    $inputFile = Join-Path $buildDir "yq_input.txt"

    if (-not (Test-Path $buildDir)) {
        New-Item -ItemType Directory -Path $buildDir -Force | Out-Null
    }

    if (-not (Test-Path $yamlQueryExe)) {
        Write-Host "  yaml_query not built, building..." -ForegroundColor Yellow
        Push-Location $projectRoot
        & moon build --target native tools/yaml_query 2>&1 | Out-Null
        Pop-Location
        if (-not (Test-Path $yamlQueryExe)) {
            Write-Host "ERROR: yaml_query build failed" -ForegroundColor Red
            return $null
        }
    }

    # Write parameters to input file (UTF-8 without BOM)
    [System.IO.File]::WriteAllText($inputFile, "$yamlPath`n$implName")

    $buildMetaJson = & $yamlQueryExe
    if ($LASTEXITCODE -ne 0 -or -not $buildMetaJson -or $buildMetaJson -eq "{}") {
        return $null
    }

    return ($buildMetaJson | ConvertFrom-Json)
}

# 鈹€鈹€鈹€ Detect current platform name 鈹€鈹€鈹€
function Get-PlatformName {
    if ($env:OS -match "Windows") { return "windows" }
    if (Test-Path "/proc/version") { return "linux" }
    return "macos"
}

Write-Host "=== Yiduo OS - WAMR Runtime Build ===" -ForegroundColor Cyan
Write-Host "Project root: $projectRoot" -ForegroundColor Gray

# 鈹€鈹€鈹€ Step 0: Read user config 鈫?determine implementation 鈹€鈹€鈹€
$implName = "wamr-real"

if (-not $Stub -and (Test-Path $bootstrapPath)) {
    $raw = Get-Content $bootstrapPath -Raw
    if ($raw -match 'implementation:\s*(\S+)') { $implName = $matches[1] }
}

if ($Stub) { $implName = "wamr-stub" }

Write-Host "Implementation: $implName" -ForegroundColor Cyan

# 鈹€鈹€鈹€ Step 0b: Read build metadata from component YAML 鈹€鈹€鈹€
$buildMeta = Get-BuildMetadata $wamrConfigPath $implName

$configHAbs = Join-Path $projectRoot "runtime/wamr/c_src/wamr_config.h"

if ($implName -eq "wamr-stub" -or -not $buildMeta -or -not $buildMeta.nativeLibrary) {
    Write-Host "Stub mode: no WAMR library needed" -ForegroundColor Yellow
    # Write wamr_config.h to force stub mode at compile time
    Set-Content -Path $configHAbs -Value "/* AUTO-GENERATED by build_wamr.ps1 */`n#define WAMR_FORCE_STUB 1`n"
    Write-Host "  wamr_config.h: WAMR_FORCE_STUB defined" -ForegroundColor Gray
    # Remove link section from moon.pkg, add cc-flags with -DWAMR_FORCE_STUB=1
    if (Test-Path $moonPkgAbs) {
        $current = Get-Content $moonPkgAbs -Raw
        $current = $current -replace '(?ms)\s*,?\s*link:\s*\{[^}]*\}[^}]*\}', ''
        $current = $current.Trim()
        # Add cc-flags to ensure stub mode even if wamr_config.h is not found
        if ($current -match "cc-flags") {
            # Already has cc-flags, leave as-is (link section removed above)
        } else {
            $current = $current -replace '\)\s*$', "`n  link: {`n    `"native`": {`n      `"cc-flags`": `"-DWAMR_FORCE_STUB=1`"`n    }`n  }`n)"
        }
        $current = $current.Trim()
        if (-not $current.EndsWith(')')) { $current = $current + "`n)" }
        Set-Content -Path $moonPkgAbs -Value $current
        Write-Host "  moon.pkg: link config removed, cc-flags added (WAMR_FORCE_STUB=1)" -ForegroundColor Gray
    }
    Write-Host "=== WAMR Build Complete (Stub Mode) ===" -ForegroundColor Cyan
    exit 0
}

# Real mode: remove wamr_config.h if it exists (let __has_include find real headers)
if (Test-Path $configHAbs) {
    Remove-Item $configHAbs -Force
    Write-Host "  wamr_config.h removed (real mode)" -ForegroundColor Gray
}

Write-Host "  build.native-library: $($buildMeta.nativeLibrary)" -ForegroundColor Gray
Write-Host "  build.include-paths: $($buildMeta.includePaths -join ', ')" -ForegroundColor Gray

# 鈹€鈹€鈹€ Derive WAMR dirs from component YAML 鈹€鈹€鈹€
# native-library path: third_party/wasm-micro-runtime/build/libvmlib.a
$buildMetaDir = Split-Path (Join-Path $projectRoot $buildMeta.nativeLibrary) -Parent
$wamrSrcDir = Split-Path $buildMetaDir -Parent    # third_party/wasm-micro-runtime
$wamrBuildDir = $buildMetaDir                     # third_party/wasm-micro-runtime/build

Write-Host "  WAMR source: $wamrSrcDir" -ForegroundColor Gray
Write-Host "  WAMR build:  $wamrBuildDir" -ForegroundColor Gray

# 鈹€鈹€鈹€ Step 1: Check tools 鈹€鈹€鈹€
Write-Host "[1/6] Checking toolchain..." -ForegroundColor Yellow
$missing = @()
foreach ($tool in @("cmake", "git")) {
    if (-not (Get-Command $tool -ErrorAction SilentlyContinue)) { $missing += $tool }
}
if ($missing.Count -gt 0) {
    Write-Host "ERROR: missing tools: $($missing -join ', ')" -ForegroundColor Red
    exit 1
}
Write-Host "  [OK] toolchain ready" -ForegroundColor Green

# 鈹€鈹€鈹€ Step 2: Fetch WAMR source (if not present) 鈹€鈹€鈹€
Write-Host "[2/6] Fetching wasm-micro-runtime..." -ForegroundColor Yellow
$hasSource = Test-Path "$wamrSrcDir/CMakeLists.txt"

if (-not $hasSource -and -not $SkipClone) {
    Write-Host "  git clone (--depth 1)..." -ForegroundColor Yellow
    if (Test-Path $wamrSrcDir) { Remove-Item -Recurse -Force $wamrSrcDir -ErrorAction SilentlyContinue }
    & git clone --depth 1 https://github.com/bytecodealliance/wasm-micro-runtime.git $wamrSrcDir
    if ($LASTEXITCODE -ne 0) {
        Write-Host "ERROR: git clone failed, fallback to stub" -ForegroundColor Red
        & $PSCommandPath -Stub
        exit 1
    }
    $hasSource = $true
    Write-Host "  [OK] source cloned" -ForegroundColor Green
} elseif ($hasSource) {
    Write-Host "  [OK] source exists" -ForegroundColor Green
} else {
    Write-Host "  [SKIP] skipping clone (use -SkipClone)" -ForegroundColor Yellow
}

# 鈹€鈹€鈹€ Step 3: Detect platform 鈹€鈹€鈹€
Write-Host "[3/6] Detecting platform..." -ForegroundColor Yellow
$platform = Get-PlatformName
Write-Host "  platform: $platform" -ForegroundColor Gray

# 鈹€鈹€鈹€ Step 4: CMake configure 鈹€鈹€鈹€
Write-Host "[4/6] CMake configure..." -ForegroundColor Yellow
if ($Rebuild -and (Test-Path $wamrBuildDir)) { Remove-Item -Recurse -Force $wamrBuildDir }
if (-not (Test-Path $wamrBuildDir)) { New-Item -ItemType Directory -Path $wamrBuildDir -Force | Out-Null }

if ($hasSource) {
    $platformPath = "$wamrSrcDir/product-mini/platforms/$platform"
    if (-not (Test-Path $platformPath)) { $platformPath = "$wamrSrcDir/product-mini/platforms/posix" }

    if (Test-Path $platformPath) {
        & cmake @(
            "-DWAMR_BUILD_INTERP=1", "-DWAMR_BUILD_AOT=0", "-DWAMR_BUILD_JIT=0",
            "-DWAMR_BUILD_LIBC_UVWASI=0", "-DWAMR_BUILD_LIB_PTHREAD=0",
            "-DWAMR_BUILD_SIMD=0", "-DWAMR_DISABLE_HW_BOUND_CHECK=1",
            "-S", $platformPath, "-B", $wamrBuildDir
        )
        if ($LASTEXITCODE -ne 0) {
            Write-Host "  product-mini failed, trying core lib..." -ForegroundColor Yellow
            & cmake @(
                "-DWAMR_BUILD_INTERP=1", "-DWAMR_BUILD_AOT=0", "-DWAMR_BUILD_JIT=0",
                "-DWAMR_BUILD_LIBC_BUILTIN=1", "-DWAMR_DISABLE_HW_BOUND_CHECK=1",
                "-S", "$wamrSrcDir/core/iwasm", "-B", "$wamrBuildDir"
            )
            if ($LASTEXITCODE -ne 0) {
                Write-Host "ERROR: CMake failed, fallback to stub" -ForegroundColor Red
                & $PSCommandPath -Stub; exit 1
            }
        }
        Write-Host "  [OK] CMake configured" -ForegroundColor Green
    }
}

# 鈹€鈹€鈹€ Step 5: Build 鈹€鈹€鈹€
Write-Host "[5/6] Building..." -ForegroundColor Yellow
$buildTool = if (Get-Command "ninja" -ErrorAction SilentlyContinue) { "ninja" }
             elseif (Get-Command "nmake" -ErrorAction SilentlyContinue) { "nmake" }
             else { "mingw32-make" }

$oldLoc = Get-Location
Set-Location $wamrBuildDir
& $buildTool -j4
$exitCode = $LASTEXITCODE
Set-Location $oldLoc

if ($exitCode -ne 0) {
    Write-Host "ERROR: build failed, fallback to stub" -ForegroundColor Red
    & $PSCommandPath -Stub; exit 1
}

# Verify libvmlib.a exists
$expectedLib = Join-Path $wamrBuildDir "libvmlib.a"
if (-not (Test-Path $expectedLib)) {
    $found = Get-ChildItem -Recurse -Filter "libvmlib.a" $wamrBuildDir | Select-Object -First 1
    if ($found) { $expectedLib = $found.FullName }
    else {
        Write-Host "ERROR: libvmlib.a not found, fallback to stub" -ForegroundColor Red
        & $PSCommandPath -Stub; exit 1
    }
}
Write-Host "  [OK] build succeeded" -ForegroundColor Green

# 鈹€鈹€鈹€ Step 6: Configure moon.pkg (from component YAML metadata) 鈹€鈹€鈹€
Write-Host "[6/6] Configuring moon.pkg..." -ForegroundColor Yellow

# Resolve include paths (from YAML spec.implementations[].build.include-paths)
$ccFlags = ""
foreach ($incPath in $buildMeta.includePaths) {
    $resolved = Join-Path $projectRoot $incPath
    if (Test-Path $resolved) {
        $ccFlags = "-I" + ($resolved.Replace('\', '/'))
    }
}

# Resolve native-library path
$libAbsPath = Join-Path $projectRoot $buildMeta.nativeLibrary
$absLibPath = $libAbsPath.Replace('\', '/')

# Resolve system-libs for current platform
$sysLibs = ""
if ($buildMeta.systemLibs -and $buildMeta.systemLibs.Contains($platform)) {
    $libList = $buildMeta.systemLibs[$platform] | ForEach-Object { "-l$_" }
    $sysLibs = $libList -join ' '
}

# Build linker-opts from template (substitute placeholders)
$linkerOpts = $buildMeta.linkerOpts
$linkerOpts = $linkerOpts.Replace('{native-library}', $absLibPath)
$linkerOpts = $linkerOpts.Replace('{system-libs}', $sysLibs)

Write-Host "  cc-flags: $ccFlags" -ForegroundColor Gray
Write-Host "  cc-link-flags: $linkerOpts" -ForegroundColor Gray

# Generate moon.pkg
$currentContent = Get-Content $moonPkgAbs -Raw

if ($currentContent -match "link:") {
    Write-Host "  [OK] moon.pkg already configured, skipping" -ForegroundColor Green
} else {
    $newContent = $currentContent.TrimEnd() -replace '\)\s*$', ''
    $newContent = $newContent + "`n  link: {"
    $newContent = $newContent + "`n    `"native`": {"
    if ($ccFlags) {
        $newContent = $newContent + "`n      `"cc-flags`": `"$ccFlags`","
    }
    $newContent = $newContent + "`n      `"cc-link-flags`": `"$linkerOpts`","
    $newContent = $newContent + "`n    },"
    $newContent = $newContent + "`n  },"
    $newContent = $newContent + "`n)"
    Set-Content -Path $moonPkgAbs -Value $newContent
    Write-Host "  [OK] moon.pkg configured from component YAML" -ForegroundColor Green
}

Write-Host "=== WAMR Build Complete (Real Mode) ===" -ForegroundColor Cyan
Write-Host "All build parameters derived from: configs/components/wamr-runtime.yaml" -ForegroundColor Cyan
Write-Host "next: moon test --target=native" -ForegroundColor Cyan