/**
 * @file native_imports.c
 * @brief WAMR native import 函数表
 *
 * 定义 WASM 模块可导入的 native 函数（通过 import "env" 声明）。
 * 当 WAMR 可用时，函数通过 `wasm_runtime_register_natives()` 注册。
 * 当 WAMR 不可用时，提供 stub 回退。
 */

#include "wamr_adapter.h"
#include <stdio.h>
#include <string.h>
#include <stddef.h>

/* WAMR_AVAILABLE is set by cc-flags in moon.pkg (generated by build_wamr.ps1 from component YAML) */
/* Real mode: -DWAMR_AVAILABLE=1 with include path to wasm_export.h */
/* Stub mode: -DWAMR_AVAILABLE=0 (or WAMR_FORCE_STUB defined in wamr_config.h) */
#if __has_include("wamr_config.h")
  #include "wamr_config.h"
#endif

#if defined(WAMR_FORCE_STUB)
  #define WAMR_AVAILABLE 0
#endif

#ifndef WAMR_AVAILABLE
  #define WAMR_AVAILABLE 0
#endif

#if WAMR_AVAILABLE
  #include "wasm_export.h"
#endif

static YiduoNativeSymbol g_native_symbols[] = {
  { "env", "send_small",      NULL, "(iii)i" },
  { "env", "register_timer",  NULL, "(i)i"   },
  { "env", "log_message",     NULL, "(iii)i" },
};

static const int g_native_symbol_count =
    sizeof(g_native_symbols) / sizeof(g_native_symbols[0]);

const YiduoNativeSymbol* get_native_symbols(int* count) {
  *count = g_native_symbol_count;
  return g_native_symbols;
}

/* ═══════════════════════════════════════════════
   真实 WAMR 模式
   ═══════════════════════════════════════════════ */

#if WAMR_AVAILABLE

static int wasm_send_small(wasm_exec_env_t exec_env,
                            int32_t from_id, int32_t to_id, int32_t msg_type) {
  (void)exec_env;
  fprintf(stderr, "[WAMR-Native] send_small(from=%d, to=%d, msg_type=%d)\n",
          from_id, to_id, msg_type);
  return 0;
}

static int wasm_register_timer(wasm_exec_env_t exec_env,
                                int32_t interval_ms) {
  (void)exec_env;
  fprintf(stderr, "[WAMR-Native] register_timer(interval=%d)\n", interval_ms);
  return 0;
}

static int wasm_log_message(wasm_exec_env_t exec_env,
                             int32_t level, int32_t msg_ptr, int32_t msg_len) {
  (void)exec_env;
  fprintf(stderr, "[WAMR-Native] log(level=%d, ptr=%d, len=%d)\n",
          level, msg_ptr, msg_len);
  return 0;
}

/** 将 YiduoNativeSymbol 转换为 WAMR NativeSymbol 并注册 */
__attribute__((constructor))
static void register_native_functions(void) {
  /* 按 module_name 分组注册 */
  int i = 0;
  while (i < g_native_symbol_count) {
    const char* module = g_native_symbols[i].module_name;
    int start = i;

    /* 计算同一 module 的符号数量 */
    int module_count = 0;
    while (i < g_native_symbol_count &&
           strcmp(g_native_symbols[i].module_name, module) == 0) {
      module_count++;
      i++;
    }

    /* 构造 WAMR 格式的 native 符号表（栈上分配） */
    NativeSymbol wamr_syms[module_count];
    for (int j = 0; j < module_count; j++) {
      int idx = start + j;
      wamr_syms[j].symbol = g_native_symbols[idx].func_name;

      /* 填入函数指针 */
      const char* name = g_native_symbols[idx].func_name;
      if (strcmp(name, "send_small") == 0)
        wamr_syms[j].func_ptr = (void*)wasm_send_small;
      else if (strcmp(name, "register_timer") == 0)
        wamr_syms[j].func_ptr = (void*)wasm_register_timer;
      else if (strcmp(name, "log_message") == 0)
        wamr_syms[j].func_ptr = (void*)wasm_log_message;
      else
        wamr_syms[j].func_ptr = NULL;

      wamr_syms[j].signature = g_native_symbols[idx].signature;
      wamr_syms[j].attachment = NULL;
    }

    wasm_runtime_register_natives(module, wamr_syms,
                                   (uint32_t)module_count);
    fprintf(stderr, "[WAMR-Native] 注册模块 '%s': %d 个函数\n",
            module, module_count);
  }
}

/* ═══════════════════════════════════════════════
   Stub 回退模式
   ═══════════════════════════════════════════════ */

#else  /* !WAMR_AVAILABLE */
/* stub 模式：符号表函数指针保持 NULL */
#endif /* WAMR_AVAILABLE */