/**
 * @file wamr_adapter.c
 * @brief WAMR 适配器实现
 *
 * 编译期自动检测 WAMR 库是否可用：
 *   1. `__has_include("wasm_export.h")` → 真实 WAMR 模式
 *   2. 否则 → Stub 回退模式（打印 stub 提示，返回失败码）
 *
 * 通过 moon.pkg 中的 native-cflags / native-linker 配置头文件路径和库链接。
 */

#include "wamr_adapter.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* --- compile-time check: WAMR availability --- */
/* WAMR_AVAILABLE is set by cc-flags in moon.pkg (generated by build_wamr.ps1 from component YAML) */
/* Real mode: -DWAMR_AVAILABLE=1 with include path to wasm_export.h */
/* Stub mode: -DWAMR_AVAILABLE=0 (or WAMR_FORCE_STUB defined in wamr_config.h) */
/*
 * wamr_config.h is generated by build_wamr.ps1 from component YAML.
 * It may define WAMR_FORCE_STUB to force stub mode at compile time.
 * Or WAMR_FORCE_STUB may be passed via cc-flags in moon.pkg.
 */
#if __has_include("wamr_config.h")
  #include "wamr_config.h"
#endif

#if defined(WAMR_FORCE_STUB)
  #define WAMR_AVAILABLE 0
#endif

#ifndef WAMR_AVAILABLE
  #define WAMR_AVAILABLE 0
#endif

#if WAMR_AVAILABLE
  #include "wasm_export.h"
#endif

/* ─── 全局状态 ─── */

WamrModuleSlot g_wamr_modules[MAX_WAMR_MODULES];
int            g_wamr_max_components = 0;
char           g_wamr_error_buf[WAMR_ERROR_BUF_SIZE] = {0};
bool           g_wamr_initialized = false;
WamrRunMode    g_wamr_run_mode = WAMR_MODE_STUB;

/* ─── 辅助函数 ─── */

static void set_error(const char* msg) {
  strncpy(g_wamr_error_buf, msg, WAMR_ERROR_BUF_SIZE - 1);
  g_wamr_error_buf[WAMR_ERROR_BUF_SIZE - 1] = '\0';
}

static int32_t slot_to_instance_handle(int32_t comp_id) {
  if (comp_id < 0 || comp_id >= g_wamr_max_components) {
    set_error("comp_id 超出范围");
    return -1;
  }
  if (!g_wamr_modules[comp_id].loaded) {
    set_error("槽位未加载");
    return -1;
  }
  return comp_id;  /* 用 comp_id 作为 handle（简化为槽位索引） */
}

/* ═══════════════════════════════════════════════
   真实 WAMR 模式实现
   ═══════════════════════════════════════════════ */

#if WAMR_AVAILABLE

int32_t wamr_runtime_init(void) {
  if (g_wamr_initialized) {
    set_error("WAMR 运行时已初始化");
    return -1;
  }

  /* 初始化 WAMR 运行时全局状态 */
  wasm_runtime_init();

  /* 清空模块槽位 */
  memset(g_wamr_modules, 0, sizeof(g_wamr_modules));
  g_wamr_initialized = true;
  g_wamr_run_mode = WAMR_MODE_REAL;

  fprintf(stderr, "[WAMR] 运行时初始化成功 (real mode)\n");
  return 1;  /* 返回非零句柄 */
}

int32_t wamr_module_load(int32_t runtime_handle, const uint8_t* wasm,
                          uint32_t wasm_size, int32_t comp_id) {
  (void)runtime_handle;

  if (!g_wamr_initialized) {
    set_error("WAMR 运行时未初始化");
    return -1;
  }
  if (comp_id < 0 || comp_id >= g_wamr_max_components) {
    set_error("comp_id 超出范围");
    return -1;
  }
  if (!wasm || wasm_size == 0) {
    set_error("空的 wasm 字节码");
    return -1;
  }

  /* 检查槽位是否已被占用 */
  if (g_wamr_modules[comp_id].loaded) {
    set_error("槽位已被占用");
    return -1;
  }

  char error_buf[128];
  /* 加载 wasm 模块 */
  wasm_module_t module = wasm_runtime_load((uint8_t*)wasm, wasm_size, error_buf, sizeof(error_buf));
  if (!module) {
    set_error(error_buf);
    return -1;
  }

  /* 实例化模块 */
  wasm_module_inst_t inst = wasm_runtime_instantiate(
      module, 8192, 8192, error_buf, sizeof(error_buf));
  if (!inst) {
    wasm_runtime_unload(module);
    set_error(error_buf);
    return -1;
  }

  /* 创建执行环境 */
  wasm_exec_env_t exec_env = wasm_runtime_create_exec_env(inst, 4096);
  if (!exec_env) {
    wasm_runtime_deinstantiate(inst);
    wasm_runtime_unload(module);
    set_error("创建执行环境失败");
    return -1;
  }

  g_wamr_modules[comp_id].loaded   = 1;
  g_wamr_modules[comp_id].module   = module;
  g_wamr_modules[comp_id].inst     = inst;
  g_wamr_modules[comp_id].exec_env = exec_env;
  snprintf(g_wamr_modules[comp_id].name, sizeof(g_wamr_modules[comp_id].name),
           "comp_%d", comp_id);

  fprintf(stderr, "[WAMR] 模块加载成功: comp_id=%d\n", comp_id);
  return comp_id;  /* 返回槽位索引作为实例句柄 */
}

int32_t wamr_module_call(int32_t instance_handle, int32_t from_id,
                          int32_t msg_type) {
  int32_t comp_id = instance_handle;
  if (comp_id < 0 || comp_id >= g_wamr_max_components) {
    set_error("无效实例句柄");
    return -1;
  }
  if (!g_wamr_modules[comp_id].loaded) {
    set_error("实例未加载");
    return -1;
  }

  wasm_module_inst_t inst = (wasm_module_inst_t)g_wamr_modules[comp_id].inst;
  wasm_exec_env_t exec_env = (wasm_exec_env_t)g_wamr_modules[comp_id].exec_env;

  /* 查找消息处理函数 "handle_message" */
  wasm_function_inst_t func = wasm_runtime_lookup_function(inst, "handle_message");
  if (!func) {
    /* 没有 handle_message 函数不是错误——wasm 模块可能没有消息处理 */
    fprintf(stderr, "[WAMR] 组件 %d 无 handle_message 函数\n", comp_id);
    return 0;
  }

  /* 准备参数: argv[0] = from_id, argv[1] = msg_type */
  uint32_t argv[2];
  argv[0] = (uint32_t)from_id;
  argv[1] = (uint32_t)msg_type;

  if (!wasm_runtime_call_wasm(exec_env, func, 2, argv)) {
    const char* exc = wasm_runtime_get_exception(inst);
    set_error(exc ? exc : "调用 wasm 函数失败");
    return -1;
  }

  return 0;
}

int32_t wamr_write_memory(int32_t instance_handle, uint32_t offset,
                           const uint8_t* data, uint32_t size) {
  int32_t comp_id = instance_handle;
  if (comp_id < 0 || comp_id >= g_wamr_max_components) {
    set_error("无效实例句柄");
    return -1;
  }
  if (!g_wamr_modules[comp_id].loaded) {
    set_error("实例未加载");
    return -1;
  }

  wasm_module_inst_t inst = (wasm_module_inst_t)g_wamr_modules[comp_id].inst;
  void* native_ptr = wasm_runtime_addr_app_to_native(inst, offset);
  if (!native_ptr) {
    set_error("无效 wasm 内存地址");
    return -1;
  }
  memcpy(native_ptr, data, size);
  return (int32_t)size;
}

int32_t wamr_read_memory(int32_t instance_handle, uint32_t offset,
                          uint8_t* data, uint32_t size) {
  int32_t comp_id = instance_handle;
  if (comp_id < 0 || comp_id >= g_wamr_max_components) {
    set_error("无效实例句柄");
    return -1;
  }
  if (!g_wamr_modules[comp_id].loaded) {
    set_error("实例未加载");
    return -1;
  }

  wasm_module_inst_t inst = (wasm_module_inst_t)g_wamr_modules[comp_id].inst;
  void* native_ptr = wasm_runtime_addr_app_to_native(inst, offset);
  if (!native_ptr) {
    set_error("无效 wasm 内存地址");
    return -1;
  }
  memcpy(data, native_ptr, size);
  return (int32_t)size;
}

void wamr_module_destroy(int32_t instance_handle) {
  int32_t comp_id = instance_handle;
  if (comp_id < 0 || comp_id >= g_wamr_max_components) return;
  if (!g_wamr_modules[comp_id].loaded) return;

  wasm_exec_env_t exec_env = (wasm_exec_env_t)g_wamr_modules[comp_id].exec_env;
  wasm_module_inst_t inst = (wasm_module_inst_t)g_wamr_modules[comp_id].inst;
  wasm_module_t module = (wasm_module_t)g_wamr_modules[comp_id].module;

  if (exec_env) wasm_runtime_destroy_exec_env(exec_env);
  if (inst)     wasm_runtime_deinstantiate(inst);
  if (module)   wasm_runtime_unload(module);

  memset(&g_wamr_modules[comp_id], 0, sizeof(WamrModuleSlot));
  fprintf(stderr, "[WAMR] 模块已销毁: comp_id=%d\n", comp_id);
}

void wamr_runtime_destroy(int32_t runtime_handle) {
  (void)runtime_handle;
  if (!g_wamr_initialized) return;

  /* 销毁所有已加载的模块 */
  for (int i = 0; i < g_wamr_max_components; i++) {
    if (g_wamr_modules[i].loaded) {
      wamr_module_destroy(i);
    }
  }

  wasm_runtime_destroy();
  g_wamr_initialized = false;
  g_wamr_run_mode = WAMR_MODE_STUB;
  fprintf(stderr, "[WAMR] 运行时已销毁\n");
}

const char* wamr_last_error(void) {
  return g_wamr_error_buf;
}

/* ═══════════════════════════════════════════════
   Stub 回退模式实现（WAMR 库不可用）
   ═══════════════════════════════════════════════ */

#else  /* !WAMR_AVAILABLE */

int32_t wamr_runtime_init(void) {
  memset(g_wamr_modules, 0, sizeof(g_wamr_modules));
  g_wamr_initialized = true;
  g_wamr_run_mode = WAMR_MODE_STUB;
  set_error("WAMR not linked: stub mode");
  fprintf(stderr, "[WAMR] runtime_init() - stub mode, WAMR not yet linked\n");
  return 0;
}

int32_t wamr_module_load(int32_t runtime_handle, const uint8_t* wasm,
                          uint32_t wasm_size, int32_t comp_id) {
  (void)runtime_handle; (void)wasm; (void)wasm_size; (void)comp_id;
  set_error("WAMR not linked: stub mode");
  fprintf(stderr, "[WAMR] module_load(comp_id=%d, size=%u) - stub mode\n",
          comp_id, wasm_size);
  return -1;
}

int32_t wamr_module_call(int32_t instance_handle, int32_t from_id,
                          int32_t msg_type) {
  (void)instance_handle; (void)from_id; (void)msg_type;
  set_error("WAMR not linked: stub mode");
  fprintf(stderr, "[WAMR] module_call(from=%d, msg=%d) - stub mode\n",
          from_id, msg_type);
  return -1;
}

int32_t wamr_write_memory(int32_t instance_handle, uint32_t offset,
                           const uint8_t* data, uint32_t size) {
  (void)instance_handle; (void)offset; (void)data; (void)size;
  set_error("WAMR not linked: stub mode");
  return -1;
}

int32_t wamr_read_memory(int32_t instance_handle, uint32_t offset,
                          uint8_t* data, uint32_t size) {
  (void)instance_handle; (void)offset; (void)data; (void)size;
  set_error("WAMR not linked: stub mode");
  return -1;
}

void wamr_module_destroy(int32_t instance_handle) {
  (void)instance_handle;
  fprintf(stderr, "[WAMR] module_destroy(handle=%d) - stub mode\n", instance_handle);
}

void wamr_runtime_destroy(int32_t runtime_handle) {
  (void)runtime_handle;
  g_wamr_initialized = false;
  fprintf(stderr, "[WAMR] runtime_destroy() - stub mode\n");
}

const char* wamr_last_error(void) {
  return g_wamr_error_buf;
}

#endif /* WAMR_AVAILABLE */